import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { Navbar } from "@/components/Header/Navbar";
import Footer from "@/components/Footer/Footer";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="vi">
        <body className={`${inter.className} relative`}>
          <Navbar />
          <EdgeStoreProvider>{children}</EdgeStoreProvider>
          <Footer />
        </body>
      </html>
    </SessionProvider>
  );
}
